version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - run:
          name: Start contract repo
          command: |
            set -x
            docker-compose up -d
      - run: mvn verify
